env:
  global:
    - secure: j97KF7KgUi/dIEBh/m+HyAmXuObQeHNQReMUAaQm48pbNvNhPr/VeBr0+gzBAS/RC31iHYjkD6Ckz0rvFlD5OzCBFvFFAuXFWR7m0Air1Veh9fCmFBwlB3TJOwBHG2HUxOr7cwy2omb3ADk9O/MnIOEsJiLvnrH8eJggTz5jbNwLdKUksgi6wCt+UfwVfeO62weydK/xuUxF4oE4zMpn46JngDDT+XfymSS0BNvAtyhsdpir4vRwSSzOQ2tLDmBufE/JKcc2oL2uqI3OCIG/s6nwnoPvgN7jhm0H8Jl7xp8up1FDOrU7Jic1C2lpVFeaSxo+ASYQyBbl5sW4Wm0n4DX8ZUqHhZBeJ3R4dcZB+leiieWLKL7hp/BaAK+x9T8IpEQ3eGweMlhIVTPdx7tuNFm8/8l9tyNTmw5bz/XkTUeCHFduGgqOPui0m2ijlJThQKZaTQWkSiZ0JuU+5eYU/t6ksBt5wt2rV6Wn24g2xwGyOMn8Bdl/e9ES4HZnRdP4ZidOlMwMleXo/AmFYhx60g1c+h/vq77TvlZn5VSQETEMFja1g6k/8j2Dbt3Lv+Go4/V/rqZjS4Br/ykDErNWOWXtpTT1MA5xlVfzQX308hq97FNfuC70C60ERmAnRc42nQXOjlTZnLBAKNS5jAbMms30mZmtze8F4ur/J1DOImY=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/WindowsSpyBlocker-update_git_crazy-max
    - GIT_BRANCH: master

language: python

python:
  - "3.6.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
