env:
  global:
    - secure: doorDItQQ9DgevNT12DDvEOunEGYdPK/9jhNDawZrImnDCncvpNoEptr1QL4VuYmA6neRPKv86llSRVvhdJsAIZGXUUuUC4d5IpFWCViTX6tja0d3F/u4YrH9dLQvJCfX+jTheG8mxHx11Z8e7AdwSYuwhTELME+zs6RGpJp1AtRuaL9E4iFtQ9zj17nQ4NpQoZhyp2v/3/hwBessgo4FHVSQ0uUcwzsFi62kfGLziBZa5Y0F/niYrzUliCpTj0YxiN7JCvOu3Q0n+IAEbPhE5+xPb+qrjRugJIQZThYeJ3lvOklSxID3Jm5G5ikZcfPp4gn0u4oML+3BJO6gW1mdNQIHbgc0Vs42GeCTC0m2ArF0h6e136Jz5geVriY6wQMYG8YzFVauxcht5bYbbsXjRaHcY/SLX6tLukCOHj0WM6cPE1IU/lqv8R9/OBG3nQOmxNhgRCoyshiAaguKgKYeWDCZVU0CZAEIkDQVpY1+HaMIvaXEeP27PjjL0hMMzMUVs+QoR3M3lK3xnV6WVOVqCA+Kp2ilffol6kOGOiz6zWHnQ2iMRl7DhQCEO/W+s9QpwU1dz+RBkRsjCp4DecETAH5kchPg3DqRw8Ko2bPkSBGNJcz3aBFGMAbjWep049/uEWU3Y88z9Lu15BKCLcszTWW0hk/g0h1XVftjBP/Qu4=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/WindowsSpyBlocker-update_git_crazy-max
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
