env:
  global:
    - secure: PEM/P6+ppyEIVZF+5jaGofgdhNPZhApmqlYz9urUhfFVjhK1FWHL2x4cfMsVsYO7lK0RMvHbjLnpPuWh7kmme2kv0iMe2uTLaURi4AKrvPln1N/Kdnrgj6kuqDe+SP8RjS0FUC47ovyh45q347/t6oED4yCoPV7JhonfGhx84m0iotTZBf3uS4CENLSMy4hHHdmRJYGT0x1d6FyXYYcBtFfQAA376z1yuqmEReVgsWduZSSSBf8d77M3l+aYDBFArbEGUi6IxCcnNdW6gaJdT/bx3meDWIhA+c8rLclmTSzBQrfK1MdRzomYirYxthuT63+y5XVRGigrzFZRX62SP+olz9+o8XWGFjIosdN5IHPVeWZYAkHooxFVqtrETei/ZBkR8KW/Vk6hFDtMFH6LRjtJv0MUcK8vN6FvH+lBOV4/OJmkzWEJ8y/BqOweoDCQBIi91twF0R8Ib5iVukMla29JSJT+dVgu4cwL05S8qHhO2xea/pmqVRl12hj/AYYpsIKWeTcDdOFU67lWbiGtb3mtSIOOKIhylInn2Jky6nNvxy/p5+JJ0R640zIToaVC8ic7LlFVpF24GfsOKxz5lwnHTWXL6mvG294DIwTk1BDno8iU1AuaVW4n1uvctbbD3QP6GhKttMd5n1H84o7PwBbEr3TiHLpyb6k58AXq7L4=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/WindowsSpyBlocker-update_git_crazy-max
    - GIT_BRANCH: master

language: python

python:
  - "3.6.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
