env:
  global:
    - secure: lQjA71R5vSiSpFteKy5XZHsEndrrue9KyoT2nzEN42wr2cN5bVw1Gw+3JKTP8VJWoW563T3bBf6RQjrPodaabTvU2SOGp3DMaLm6IPQUanHT2TA7ourTzqQ++g1ryigR2YEJZpM2MBRphZY9stk6bHHZ+SdAT/l3/g0f1EDN7wZaQoeBq5fBTRHLbmTBQCzvyyD64UZ9nFh9/inBWMa6KrP1SR790K8b989N9rgSDkcmPyTGgyGUV1Y5raYySNHxJZpjuZGr88EPjveaPKvtHk0R+cIMW3csIj/e6+1LgqI215Ssw6kLafxdZGoHOPF/qSAA+atgrvUUWCyXcn9zE2AuDXDM2ycYn1P72ebCdqo2VQX/9yXHtdqhdAN33Oo4v97dZTN2bWVrJz8gCJ1leXwAZAk9poaDSo0UZfmQvQ34Ux55aDM0XYEyQy/HasPQRKn5MCgfj2P6zDn/6Kphc2Upky8vBhickQh3ssaPJtBtB00zrFvEZThErbbQ8+OAeEF3OWZvRMii28RcxbXuF0AU64dapNH8Jhk9IrTDrndSFsnCJKXC3kZKijXBV6DdcIrTob/40b1tiUczdsDbGQkykWqec55Wce/be0nRPIX1nKYiIGvAXjvnIBRXxjcB669oZe6DH5D+NSnE6y19zgFvk76cyFo4OSite8M9JFg=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/WindowsSpyBlocker-update_git_crazy-max
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install pyfunceble-dev
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
