env:
  global:
    - secure: O/1Dp7IZiMfr1bt4WF5jLeRokYo/ec8uBYHD6wXYfhZeXg/Y+X28/ZDef0VevHWzJokhvxQZlYqqxazVELv3JeCREFp9EIcGvF3LfJUdn2QiCSAl5fkPJnm23iW04VVDM8jY4K/1NGOux0yj3z4f+Cd3i2PIiJKYXWaZbmMbve6cpChj+N1UkEOyNCDtFQ3m0cM/z2cNJ5arGHFNuhVsKGCnM6LeSLteCXk6bKHxD+BXf720HynmKPkFExuaB995gE5IEY8FmT6ux0ib1vceiA0mcZGZ4Q14jSzmIVlmvhA1TIsjR6459Ikl42g+74VHprwjAhMiFV7bf+dyJYiE9WjmTPz6jUgZx4MllE7B9n8Yxll6BbqLc5NaS6794dgYq0vJ+FuVKy2/90fZMie/f+Ta/XzB+bj6uRuccid/HQDTOlK+UYeeSTUSWqVr8KzrCTxLfHjXirwwRZivoLolpILZoZtQobIf+YqQ1V3xhw50ymmxSYupstBhJ2OO6UlSamy5ZUqOFElh5b0Fwz3DPpEs+F1hqzVavl7Ka3aPQDy6TxrTT/E6n2cGdj4A5jMA0g7R5I3cCR6RPF8w+RKNOdkZ/6/wHPaM/5VIqAVnjSg7UQP8tB7yhlrmwlkAHLxDnJW66pn9NyXxXt94yWXJDHR8+0fvOjuRvI8CZu6FJo8=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/WindowsSpyBlocker-update_git_crazy-max
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install pyfunceble-dev
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
