env:
  global:
    - secure: kAOUMf7pmK3KyuoRCP2kY4o40FafGr/S0UqHDQgg9UZ4eh/Ei/XCYrnLcOb3cXeS6Uv9NdP6HNEsqEUsrhKp9KlLCgF1Q48HRXQW/BkOEAIl1COgykp+hWCxDN8jMox9Y6AbIaf9fQKSiZmPYAinf1nShtbRJ73O/eh6uvOneuuzNnrn6rneFpxgzv3Woz9Bh3mA0nepRRBpQp2D7qS/IK8S3mHRMJOmxizFSX6OZkrDWgyE46PYd4POdBBXttrSxxPbUO/Mvj8M6E17PVWr92vLm7YXUC/XRQ5qofsHK0PK598j6aob/SdIv8bCRAI55/qVWwdn79wYMI/g02WPnzkNHVDeC0j4yOpnLvR1IqYQWxL07f4H/TOERWenPF3Pod3c+ZkZFKJlUhoLq5pokLsErQ9slgwa4X4gR5yE5J3CpdW2OYyaQ+EOgcfIMmccr5/xnoAI0PaNwougdqbKoU7M5TKMl/NUABEawTnFOnfQHSyc7Tg/aQbLIgDK/fNVI0KnnpBVlFLgSafykpytYduVJOvInP5q0D5kNTA4FbkgjDk5WImGXsFztojIT48s3w4Lgff6ciyiNx5G3UiAI0j53VxfGCcCIHmhQ4LrgCiE1H2Hz2lPHWkLXN8TqsnyP4no/imFsBvgcF4K+dj/5Za33TDGLC1K6F0d5s2zO+k=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/WindowsSpyBlocker-update_git_crazy-max
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
