env:
  global:
    - secure: ndMhJGt0J6bgw1RGL8qXfdgxsBu8plyKcugeKyFk0E/ZvlAWTcwOrXXTiSiEePNrHoCPCpwbCmw7pPkpRYBJA3Jbs/sp21Y7z3VMSFVHJYmcu3z531hCR1PIc8H9fLNcezMzO/BVxZpcNe1NaPiC78foTm17DKWi9n6LZ6PtfWYozxK5b2fmnpDWh/84SFbYbqHDUsyWQuh3Biu9TRyYVEzgjYt08cacVUc7Z/ysZS5IPoDfjFTr95d78Wl8A8+Tiuzasy5SQucOLdfkWKXrs/RFYDcEK6YlxT2cM/bG0/4cai7t0C6spx67Lpct1lF8qaAxiIJ+ULqgGXSLqYjfSznizsywM9W2ghhI+NEvDUoTpT0LBb3IA5UQbf/gg+ixqI1lKTtdnjTdQ0GaP37hYlZ7PrCan50Z2D+/tSDmrH53zh4CTvJEeSVlbNA2v+GWdzV/QC5UqOYJZ9sGHHVWgb8i8Ly7AwZNyJ0VeJsfdrO88FrRJv9FqVcIfyB0HaMUSAVstV1C73OKo9Elx4Y21madROaFr220Wn29F9t2SFpwGDEI59PJdp0MYsNef8GQSxbMksLIfo3YAE7ZVWMq/crRNDCCe4T81AnpoRr3pOjwA/qw08f9f5wv6MAGDahtZxOjvdZcwBNUT9dsTI/F2OKgue62Rwrpcwd1Eu5shMY=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/WindowsSpyBlocker-update_git_crazy-max
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install pyfunceble-dev
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
